"""phase6_initial_vouchers

Revision ID: xxxxxxxxxxxx  # This is auto-generated, don't change
Revises: previous_id  # Auto-generated from chain
Create Date: 2025-07-26 00:00:00.000000  # Approx

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'xxxxxxxxxxxx'  # Auto-generated
down_revision = 'previous_id'  # Auto-generated
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(sa.table('voucher_types',
        sa.column('name', sa.String()),
        sa.column('module_name', sa.String()),
        sa.column('category', sa.String())
    ), [
        {'name': 'Purchase', 'module_name': 'purchase_inv', 'category': 'purchase'},
        {'name': 'Receipt Note', 'module_name': 'receipt_note', 'category': 'purchase'},
        {'name': 'Purchase Order', 'module_name': 'purchase_order', 'category': 'purchase'},
        {'name': 'Rejection Out', 'module_name': 'rejection_out', 'category': 'purchase'},
        {'name': 'Sales', 'module_name': 'sales_inv', 'category': 'sales'},
        {'name': 'Delivery Note', 'module_name': 'delivery_challan', 'category': 'sales'},
        {'name': 'Sales Order', 'module_name': 'sales_order', 'category': 'sales'},
        {'name': 'Rejection In', 'module_name': 'rejection_in', 'category': 'sales'},
        {'name': 'Quotation', 'module_name': 'quotation', 'category': 'sales'},
        {'name': 'Proforma Invoice', 'module_name': 'proforma_invoice', 'category': 'sales'},
        {'name': 'Credit Note', 'module_name': 'credit_note', 'category': 'sales'},
        {'name': 'Receipt', 'module_name': 'receipt', 'category': 'financial'},
        {'name': 'Payment', 'module_name': 'payment', 'category': 'financial'},
        {'name': 'Contra', 'module_name': 'contra', 'category': 'financial'},
        {'name': 'Journal', 'module_name': 'journal', 'category': 'financial'},
        {'name': 'Stock Journal', 'module_name': 'stock_journal', 'category': 'internal'},
        {'name': 'Physical Stock', 'module_name': 'physical_stock', 'category': 'internal'},
        {'name': 'Payroll', 'module_name': 'payroll', 'category': 'internal'},
        {'name': 'Attendance', 'module_name': 'attendance', 'category': 'internal'},
        {'name': 'GRN', 'module_name': 'grn', 'category': 'purchase'},
        {'name': 'Internal Return', 'module_name': 'internal_return', 'category': 'internal'},
        {'name': 'Debit Note', 'module_name': 'debit_note', 'category': 'financial'}
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM voucher_types WHERE category IN ('purchase', 'sales', 'financial', 'internal')")
    # ### end Alembic commands ###